### ISSUE TITLE
No implementation found for method init on channel flutter_audio_recorder2

### ISSUE THREAD

**Issue by lancer1993** [hanyska/flutter_audio_recorder2#11]
I got this issue when I tried apply flutter_audio_recorder2 to my flutter app. Is  this a bug or not ? 
Comment If there any perfect documentation for developers.

E/flutter (20963): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method init on channel flutter_audio_recorder2)
E/flutter (20963): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:165:7)
E/flutter (20963): <asynchronous suspension>
E/flutter (20963): #1      FlutterAudioRecorder._init (package:coco_App/common/audio_recorder.dart:68:18)
E/flutter (20963): <asynchronous suspension>
E/flutter (20963): #2      _StepTwoEnglishState._initial (package:coco_App/page/english/apata_kiyanna/step_two.dart:301:7)
E/flutter (20963): <asynchronous suspension>
E/flutter (20963): #3      _StepTwoEnglishState._recordo (package:coco_App/page/english/apata_kiyanna/step_two.dart:278:7)
E/flutter (20963): <asynchronous suspension>

**Comment by Kee3f** [comment]
I am also facing this error,Do you other way?

**Comment by ITcians** [comment]
Please stop your running flutter app and rerun the app using `flutter run`.
It happens when you add native plugins which needs to by synced with your running flutter app and thats only done when you run above command. So each time you use a native plugin then Stop the app and rerun.
